### PR TITLE
code refactoring

### PR DESCRIPTION
**Pull request by daedalus**

### CODE REVIEW

**Comment by ReverseControl** [comment]
You need to break this up and comment on what you are doing.

**Comment by daedalus** [comment]
Best practices applied.
Pep8 compliant.
If you look a this changes I think you will understand why I have sent them.

**Comment by ReverseControl** [comment]
Yes, I would understand....after taking a very long time to figure out what you did. Split them up into commits and comment on each commit what you are doing. Having to reverse engineer such a large commit is not something I have time to do. The point is clarity and ease of reading.

**Comment by daedalus** [comment]
What a waste of time

**Pull request closed without merging**
